# Generated by Django 3.0.3 on 2020-04-23 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transhis',
            name='transDate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
